# Dockerfile для базы данных
FROM postgres:13

# Копирование скрипта инициализации базы данных
COPY init.sql /docker-entrypoint-initdb.d/

# Переменные окружения для базы данных
ENV POSTGRES_DB=purchases
ENV POSTGRES_USER=testing_test
ENV POSTGRES_PASSWORD=Test_n0w@day$