version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  web:
    build: .
    command: bash -c "python init_db.py && python web.py"
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
